// <auto-generated />
using System;
using HrPlatformProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrPlatformProject.Migrations
{
    [DbContext(typeof(MydbContext))]
    [Migration("20260510162217_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");

            modelBuilder.Entity("Candidateskill", b =>
                {
                    b.Property<int>("SkillsIdskills")
                        .HasColumnType("int")
                        .HasColumnName("skills_idskills");

                    b.Property<int>("CandidatesIdcandidates")
                        .HasColumnType("int")
                        .HasColumnName("candidates_idcandidates");

                    b.HasKey("SkillsIdskills", "CandidatesIdcandidates")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "CandidatesIdcandidates" }, "fk_skills_has_candidates_candidates1_idx");

                    b.HasIndex(new[] { "SkillsIdskills" }, "fk_skills_has_candidates_skills_idx");

                    b.ToTable("candidateskills", (string)null);
                });

            modelBuilder.Entity("HrPlatformProject.Models.Candidate", b =>
                {
                    b.Property<int>("Idcandidates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcandidates");

                    b.Property<int?>("ContactNumber")
                        .HasColumnType("int")
                        .HasColumnName("contactNumber");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Idcandidates")
                        .HasName("PRIMARY");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("candidates", (string)null);

                    b.HasData(
                        new
                        {
                            Idcandidates = 1,
                            ContactNumber = 641234567,
                            DateOfBirth = new DateOnly(2000, 3, 15),
                            Email = "marko@gmail.com",
                            Name = "Marko Markovic"
                        },
                        new
                        {
                            Idcandidates = 2,
                            ContactNumber = 659876543,
                            DateOfBirth = new DateOnly(1998, 7, 22),
                            Email = "ana@gmail.com",
                            Name = "Ana Jovanovic"
                        });
                });

            modelBuilder.Entity("HrPlatformProject.Models.Skill", b =>
                {
                    b.Property<int>("Idskills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idskills");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Idskills")
                        .HasName("PRIMARY");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Idskills = 1,
                            Name = "C# programming"
                        },
                        new
                        {
                            Idskills = 2,
                            Name = "Java programming"
                        },
                        new
                        {
                            Idskills = 3,
                            Name = "Database design"
                        },
                        new
                        {
                            Idskills = 4,
                            Name = "English language"
                        },
                        new
                        {
                            Idskills = 5,
                            Name = "Russian language"
                        },
                        new
                        {
                            Idskills = 6,
                            Name = "German language"
                        });
                });

            modelBuilder.Entity("Candidateskill", b =>
                {
                    b.HasOne("HrPlatformProject.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesIdcandidates")
                        .IsRequired()
                        .HasConstraintName("fk_skills_has_candidates_candidates1");

                    b.HasOne("HrPlatformProject.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsIdskills")
                        .IsRequired()
                        .HasConstraintName("fk_skills_has_candidates_skills");
                });
#pragma warning restore 612, 618
        }
    }
}
